name: valentines-day
version: 0.0.1.0

dependencies:
  - base

library:
  exposed-modules: ValentinesDay
  source-dirs: src
  ghc-options: -Wall -fplugin=Polysemy.Plugin
  dependencies:
  - aeson
  - optparse-generic
  - servant
  - polysemy
  - polysemy-plugin
  - massiv

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - valentines-day
      - hspec
